spring:
  profile:
    active: mysql
  datasource:
    username: eslota
    password: ${MORFEUSZ_PASSWORD}
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=eslota;encrypt=false;
  jpa:
    hibernate:
      ddl-auto: create-drop
